### ISSUE TITLE
`setuptools_scm_git_archive` is obsolete since setuptools_scm version 7

### ISSUE THREAD

**Issue by frenzymadness** [fonttools/pyclipper#52]
setuptools_scm version 7 and newer supports Git archives by itself. The migration guide is available in the [Readme](https://github.com/Changaco/setuptools_scm_git_archive#readme) of the project.

The problem is, that the plugin [is not compatible](https://github.com/Changaco/setuptools_scm_git_archive/issues/23) with setuptools_scm 8, and the incompatibility might break your builds.

**Comment by anthrotype** [comment]
Can you send a PR? I'll gladly merge that, thanks

**Comment by anthrotype** [comment]
Ah I just saw there is already one, but it doesn't follow the instructions from their Readme that you linked above:

https://github.com/fonttools/pyclipper/pull/49
