### ISSUE TITLE
Provide wheel for Python 3.13

### ISSUE THREAD

**Issue by martinRenou** [fonttools/pyclipper#58]
Hello there!

It looks like there is no wheel available for Python 3.13. It would be great if that could be published, thanks!

**Comment by anthrotype** [comment]
we'll make one soon, thanks for thre reminder 👍

**Comment by anthrotype** [comment]
python 3.13 wheels should be up now at https://pypi.org/project/pyclipper/1.3.0.post6/#files

**Comment by martinRenou** [comment]
Neat thanks!
